### PR TITLE
Missed a full stop.

### PR DESCRIPTION
**Pull request by pa9ey**
Sorry! :)

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/threecopies#9` is in scope.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/threecopies#9` is already in scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.3`

**Pull request merged**
